# Copyright 2024 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

repos:
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
  - id: insert-license
    name: "Insert license header in C++ source files"
    args: ["--license-filepath=.github/LICENSE.tmpl"]
